version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ulitov
      POSTGRES_PASSWORD: timur
      POSTGRES_DB: Ulitov
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  player_service:
    container_name: player_service
    build: player_service/
    ports:
      - "8000:80"
    depends_on:
      - db

  roulette_service:
    restart: on-failure
    container_name: roulette_service
    build: ./roulette_service/
    ports:
      - "8001:80"
    depends_on:
      - db
